server:
  port: 9192

spring:
  application:
    name : Lakeside-Hotel
  datasource:
    url: jdbc:postgresql://localhost:5432/lakesidehotel
    username: postgres
    password: 123
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#https://www.youtube.com/watch?v=0XJu4Nnl0Kc&t=523s